Programmer.exe: Decompiled/BandMemory.cs  Decompiled/Category.cs  Decompiled/Database.cs  Decompiled/DataConverter.cs  Decompiled/DataForm.cs  Decompiled/DtmfMemory.cs  Decompiled/Group.cs  Decompiled/MessageText.cs  Decompiled/Moji.cs  Decompiled/Settings.cs  Dumper.cs Geocoder.cs CSV.cs Programmer.cs
	mcs /reference:System.Net.Http.dll Programmer.cs CSV.cs Dumper.cs Geocoder.cs Encoder.cs Decompiled/BandMemory.cs  Decompiled/Category.cs  Decompiled/Database.cs  Decompiled/DataConverter.cs  Decompiled/DataForm.cs  Decompiled/DtmfMemory.cs  Decompiled/Group.cs  Decompiled/MessageText.cs  Decompiled/Moji.cs  Decompiled/Settings.cs
run: Programmer.exe
	chmod +x Programmer.exe
	./Programmer.exe CLNFTM400D.dat Repeaters.csv CLNFTM400D.dat.new
clean:
	rm ../Programmer.exe Programmer.exe ../source.html ../destination.html ../CLNFTM400D.dat.new
